title: Around Sketch
email: aroundsketch@pm.me
description: >- # this means to ignore newlines until "baseurl:"
  Set of icons masterfully recreated in Sketch
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
